POST http://localhost:8090/content/jsonStr
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "name": "sdc",
  "email": "yuki@vip.com",
  "hoibby": "sleep"
}
###
POST http://localhost:8090/content/xml
Content-Type: application/xml
Accept: application/xml
Cache-Control: no-cache

<ParamData>
    <name>Jim</name>
    <age>2</age>
</ParamData>
###

POST http://localhost:8090/content/form1?name=LiLi&age=11
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache



### Path校验
GET http://localhost:8090/validate/path/aaa++/1
Accept: application/json
Cache-Control: no-cache


###
GET http://localhost:8090/validate/param?group=sdc&userid=1
Accept: application/json
Cache-Control: no-cache

###
POST http://localhost:8090/validate/form?email=sdc
Accept: application/json
Cache-Control: no-cache

###
POST http://localhost:8090/validate/json
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{"email":"sdc"}

###