### test
GET http://localhost:8080/test?name=H
Accept: application/json
Cache-Control: no-cache

### test2
GET http://localhost:8080/test2?name=Hello&price=0
Accept: application/json
Cache-Control: no-cache


### test3
GET http://localhost:8080/test3?date=aqq
Accept: application/json
Cache-Control: no-cache

### test insert
GET http://localhost:8080/insert?name=Hello&price=0

### test update
GET http://localhost:8080/update?name=Hello&price=0

###

